config/routes.rb
Rails.application.routes.draw do
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  post '/users/edit', to: 'users#update'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  
  get '/all-requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'

  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post '/users/edit_phone', to: 'users#callback_phone'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accepted', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  resources :requests
  
  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end

  devise_for :users, 
              path: "", 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  root 'pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :gigs
  has_many :requests
  has_many :offers

  has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
  has_many :selling_orders, foreign_key: "seller_id", class_name: "Order"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

  validates :full_name, presence: true, length: { maximum: 50 }

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      if !user.provider
        user.update(uid: auth.uid, provider: auth.provider, image: auth.info.image)
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider
      end
    end
  end

  def hidden_phone
    if self.phone && self.phone.length > 3
      "*" * (self.phone.length - 3) + self.phone.last(3)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def dashboard
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.where(seller_id: params[:id]).order("created_at desc")
  end

  def update
    @user = current_user
    if @user.update_attributes(current_user_params)
      flash[:notice] = "Saved"
    else
      flash[:error] = "Cannot update..."
    end
    redirect_to dashboard_path
  end

  def callback_phone
    path_access_token = "https://graph.accountkit.com/v1.1/access_token?" +
                        "grant_type=authorization_code" +
                        "&code=#{params[:code]}" +
                        "&access_token=AA|#{754486548345637}|#{"b32042a416491a5d7bf7abbf81627392"}"

    response = Net::HTTP.get(URI.parse(path_access_token))
    response = JSON.parse(response)

    if response['access_token']
      path_get_data = "https://graph.accountkit.com/v1.1/me?access_token=#{response['access_token']}"
      response = Net::HTTP.get(URI.parse(path_get_data))
      response = JSON.parse(response)

      if response['phone']['number']
        current_user.update(phone: response['phone']['number'])
        return render json: {success: true}
      end
    end

    return render json: {success: false}
  end

  def update_payment
    if !current_user.stripe_id
      customer = Stripe::Customer.create(
        email: current_user.email,
        source: params[:stripeToken]
      )
    else
        customer = Stripe::Customer.update(
          current_user.stripe_id,
          source: params[:stripeToken]
        )
    end

    if current_user.update(stripe_id: customer.id, stripe_last_four: customer.sources.data.first["last4"])
      flash[:notice] = "New Card is saved"
    else
      flash[:error] = "Invalid card"
    end
    redirect_to request.referrer
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to request.referrer
  end

  def update_payout
    if current_user.update(paypal: params[:paypal])
      flash[:notice] = "Update payout successfully"
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_to request.referrer
  end

  private

  def current_user_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/payment.html.erb
<style>
    /**
    * The CSS shown here will not be introduced in the Quickstart guide, but shows
    * how you can use CSS to style your Element's container.
    */
    .StripeElement {
    box-sizing: border-box;

    height: 40px;

    padding: 10px 12px;

    border: 1px solid transparent;
    border-radius: 4px;
    background-color: white;

    box-shadow: 0 1px 3px 0 #e6ebf1;
    -webkit-transition: box-shadow 150ms ease;
    transition: box-shadow 150ms ease;
    }

    .StripeElement--focus {
    box-shadow: 0 1px 3px 0 #cfd7df;
    }

    .StripeElement--invalid {
    border-color: #fa755a;
    }

    .StripeElement--webkit-autofill {
    background-color: #fefde5 !important;
    }
</style>

<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8-tablet is-6-desktop is-6-widescreen">
                <p class="title has-text-centered">Payment Method</p>

                <% if current_user.stripe_last_four %>
                  <div class="card">
                    <div class="card-header-title is-centered">
                      <%= "Your current card: **** **** **** #{current_user.stripe_last_four}" %>
                    </div>
                  </div>
                <% end %>

                <%= form_with url: update_payment_path, local: true, id: "payment-form" do |f| %>
                    <div class="card form-row">
                        <div id="card-element">
                        <!-- A Stripe Element will be inserted here. -->
                        </div>

                        <!-- Used to display form errors. -->
                        <div id="card-errors" role="alert"></div>
                    </div>

                    <div class="field is-grouped is-grouped-centered">
                        <%= f.submit "#{current_user.stripe_id ? "Update Card" : "Add Card"}", class: "button is-primary card" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

<script>
        // Create a Stripe client.
    var stripe = Stripe('<%= Rails.application.credentials[Rails.env.to_sym][:stripe][:STRIPE_PUBLIC_KEY] %>');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
        base: {
            color: '#32325d',
            fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
            fontSmoothing: 'antialiased',
            fontSize: '16px',
            '::placeholder': {
            color: '#aab7c4'
            }
        },
        invalid: {
            color: '#fa755a',
            iconColor: '#fa755a'
        }
    };

    // Create an instance of the card Element.
        var card = elements.create('card', {style: style});

        // Add an instance of the card Element into the `card-element` <div>.
        card.mount('#card-element');

        // Handle real-time validation errors from the card Element.
        card.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
            displayError.textContent = event.error.message;
        } else {
            displayError.textContent = '';
        }
        });

    // Handle form submission.
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
        event.preventDefault();

        stripe.createToken(card).then(function(result) {
            if (result.error) {
            // Inform the user if there was an error.
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
            } else {
            // Send the token to your server.
            stripeTokenHandler(result.token);
            }
        });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
        var form = document.getElementById('payment-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // Submit the form
        form.submit();
        }
</script>

app/views/users/payout.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8-tablet is-6-desktop is-6-widescreen">
                <p class="title has-text-centered">Payout Method</p>
                <%= form_with url: update_payout_path, local: true do |f| %>
                    <div class="field">
                        <%= f.text_field :paypal, value: current_user.paypal, placeholder: "Your Paypal Email", class: "input" %>
                    </div>
                    <div class="field is-grouped is-grouped-centered">
                        <%= f.submit "Save", class: "button is-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
        
        <!-- LEFT SIDE -->
        <div class="column is-one-third">
            <div class="columns is-multiline">

                <!-- Top Card -->
                <div class="column is-full">
                    <div class="card">

                        <!-- Avatar -->
                        <div class="card-content is-horizontal-center is-flex">
                            <figure class='image is-128x128'>
                                <%= image_tag avatar_url(@user), class: 'is-rounded' %>
                            </figure>
                        </div>
                        
                        <div class="card-content">

                            <!-- Upload Button -->
                            <div class="content has-text-centered">
                                <p class='title is-5'><%= @user.full_name %></p>
                            </div>
                            <hr class="h-10">
                            
                            <!-- Member -->
                            <article class="media">
                                <div class='media-content'>Member since</div>
                                <div class='media-right'><strong><%= @user.created_at.strftime('%b %Y') %></strong></div>
                            </article>
                            <hr class="h-10">
                            
                            <!-- From -->
                            <article class='media'> 
                                <div class='media-content'>From</div>
                                <div class='media-right'>
                                    <%= @user.from %>
                                </div>
                            </article>                                
                            <hr class="h-10">

                            <!-- Online Status -->
                            <article class='media'>
                                <div class='media-content'>Online Status</div>
                                <div class='media-right'>
                                    <strong><% if @user.status %> Online <% else %> Offline <% end %></strong>
                                </div>
                            </article>

                        </div>
                    </div>
                </div>

                <!-- Bottom Card -->
                <div class="column is-full">
                    <div class="card">
                        <div class="card-content">

                            <!-- About -->
                            <article class='media'>
                                <div class='media-content'>
                                    <p>
                                        <strong>About Yourself</strong><br />
                                        <%= @user.about %>
                                    </p>
                                </div>
                                <div class='media-right'>
                                    <i class='toggle far fa-edit' aria-controls='user-about'></i>
                                </div>
                            </article>
                            <hr class="h-10">

                            <!-- Language -->
                            <article class='media'>
                                <div class='media-content'>
                                    <p>
                                        <strong>Language(s)</strong><br />
                                        <%= @user.language %>
                                    </p>
                                </div>
                            </article>
                            <hr class="h-10">
                            
                            <!-- Linked Account -->
                            <article class="media">
                                <div class='content'>
                                    <p>
                                        <strong>Linked Account</strong><br />
                                        <% if @user.uid %>
                                            <span class='has-text-success'>Facebook verified</span>
                                        <% else %>
                                            <span class='has-text-danger'>Facebook unverified</span>
                                        <% end %>
                                    </p>
                                </div>
                            </article>

                            <!-- Mobile Number -->
                            <article class="media">
                                <div class='content'>
                                    <p>
                                        <strong>Mobile Number</strong><br />
                                        <% if @user.phone %>
                                            <span class='has-text-success'>Mobile # verified</span>
                                        <% else %>
                                            <span class='has-text-danger'>Mobile # unverified</span>
                                        <% end %>
                                    </p>
                                </div>
                            </article>

                        </div>
                    </div>
                </div>

            </div>
        </div>

        <!-- RIGHT SIDE -->
        <div class="column">

        <div class="columns is-multiline">
         <!-- Sample Gig -->
                <% @user.gigs.each do |gig| %>
                    <div class="column is-one-third">
                        <div class="card">
                            <div class="card-image">
                            <%= link_to edit_gig_path(gig) do %>
                                <figure class="image is-4by3">
                                    <%= image_tag gig_cover(gig) %>
                                </figure>
                                <% end %>
                            </div>

                            <div class="card-content p-t-5 p-b-5">
                                <p class="subtitle is-6 m-b-5"><%= link_to gig.title, gig_path(gig) %></p>
                                <span class="star-review"><i class="fa fa-star"></i>
                                    <%= gig.average_rating %>
                                <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
                                </span>
                            </div>

                            <footer class="card-footer">
                                <% basic_price = gig.pricings.find{ |p| p.pricing_type == 'basic' } %>
                                <% if !basic_price.nil?%>
                                    <a class="has-text-danger is-block card-footer-item has-text-right">
                                        <span class="small-title">STARTING AT</span>
                                        <strong>$<%= basic_price.price %></strong>
                                <% else %>
                                    <strong>
                                        <span class="small-title has-text-dark">NO PRICING YET</span>
                                    </strong>
                                <% end %>
                                    </a>
                            </footer>
                            </div>
                        </div>
                <% end %>
            </div>

            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">Latest Reviews</div>
                </div>
                <div class='card-content'>
                    <!-- Sample Reviews -->
                    <% @reviews.each do |r| %>
                        <article class='media'>
                            <figure class='media-left'>
                                <p class='image is-64x64'>
                                    <%= image_tag avatar_url(r.buyer), class: 'is-rounded' %>
                                </p>
                            </figure>
                            <div class='media-content'>
                                <div class='content'>
                                    <p>
                                        <strong><%= r.buyer.full_name %></strong><br/>
                                        <%= r.review %>
                                    </p>
                                    <small><%= time_ago_in_words r.created_at %></small>
                                </div>
                            </div>

                            <div class='media-right'>
                                <span class='star-review'><i class='fa fa-star'></i> <%= r.stars %></span>
                            </div>
                        </article>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>