config/routes.rb
Rails.application.routes.draw do
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  post '/users/edit', to: 'users#update'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  
  get '/all-requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'

  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post '/users/edit_phone', to: 'users#callback_phone'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accepted', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  resources :requests
  
  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end

  devise_for :users, 
              path: "", 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  root 'pages#home'
end

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index: 5">
    <div class="container">
        <div class="navbar">
            <% @categories.each do |category| %>
                <%= link_to "#{category.name}", search_path(category: category.id), class: "navbar-item" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/shared/_gigs.html.erb
<% @gigs.each do |gig| %>
        <div class="column is-one-third">
            <div class="card">
                <div class="card-image">
                <%= link_to gig_path(gig) do %>
                    <figure class="image is-4by3">
                        <%= image_tag gig_cover(gig) %>
                    </figure>
                    <% end %>
                </div>

                <div class="card-content p-t-5 p-b-5">
                    <p class="subtitle is-6 m-b-5"><%= link_to gig.title.truncate(20), gig_path(gig) %></p>
                    <span class="star-review"><i class="fa fa-star"></i>
                        <%= gig.average_rating %>
                    <span class="has-text-primary">(<%= gig.reviews.count %>)</span>
                    </span>
                </div>

                <footer class="card-footer">
                    <span class="card-footer-item">
                    <%= link_to users_path(gig.user) do %>
                        <figure class="image is-32x32">
                            <%= image_tag avatar_url(gig.user), class: "is-rounded" %>
                        </figure>
                    <% end %>
                    </span>
                    <a class="has-text-danger is-block card-footer-item has-text-right">
                        <span class="small-title">STARTING AT</span>
                        <strong>$<%= gig.price %></strong>
                    </a>
                </footer>
            </div>
        </div>
<% end %>

app/views/shared/_navbar.html.erb
  <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
      <div class="navbar-brand"></div>
        <a class="navbar-item" href="/">
          <h1 class='title is-4'>Freelancer</h1>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <div class="navbar-item">
              <%= form_tag search_path, method: :get do %>
                <div class="field has-addons <%= 'is-hidden' if current_page?(root_path) %>">
                    <div class="control has-icons-left">
                        <span class="icon is-small is-left">
                            <i class="fa fa-search"></i>
                        </span>
                        <%= text_field_tag 'q', '', class: "input", placeholder: "Try 'logo design'" %>
                    </div>
                    <div class="control">
                        <button class="button is-danger" type="submit">Search</button>
                    </div>
                  </div>
              <% end %>
            </div>
          </div>
          
          <div class="navbar-end">
            <%= link_to 'Post Gig', new_gig_path, class: "navbar-item" %>
            <%= link_to 'Browse Gigs', search_path, class: "navbar-item" %>

              <% if (!user_signed_in?) %>
                <div class="navbar-item">
                  <div class="buttons">
                    <%= link_to 'Sign Up', new_user_registration_path, class: 'button is-primary' %>
                    <%= link_to 'Login', new_user_session_path, class: 'button is-light' %>
                  </div>
              </div>
              <% else %>

              <div class="navbar-item dropdown is-hoverable">
                <a class='navbar-link'>
                  <figure class='image is-24x24 m-r-5 avatar <%= current_user.status ? "online" : "offline" %>'>
                    <%= image_tag avatar_url(current_user), class: 'is-rounded' %>
                  </figure>
                  <%= current_user.full_name %>
                </a>
    
                <div class="navbar-dropdown">
                <%= link_to 'Profile', edit_user_registration_path, class: 'navbar-item' %>
                  <%= link_to 'Dashboard', dashboard_path, class: 'navbar-item' %>
                  <hr class="navbar-divider">
                  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-item' %>
                </div>
              </div>
              <% end %>
          </div>
      </div>
  </nav>

  <% if (user_signed_in?) && !current_page?(root_path) && !current_page?(search_path) && !current_page?("/gigs/#{params[:id]}") && !current_page?("/users/#{params[:id]}") %>

    <nav class='navbar has-shadow' style='z-index: 5'>
      <div class="container">
        <div class="navbar">
          <%= link_to 'Dashboard', dashboard_path, class: 'navbar-item' %>
          <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">Selling</a>
              <div class="navbar-dropdown">
                <%= link_to 'Create New Gig', new_gig_path, class: "navbar-item" %>
              </div>
            </div>

          <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">Buying</a>
              <div class="navbar-dropdown">
                <%= link_to "Post Request", new_request_path, class: "navbar-item" %>
                <%= link_to "Manage Requests", requests_path, class: "navbar-item" %>
              </div>
            </div>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Buyer Request</a>
                <div class="navbar-dropdown">
                <%= link_to "Active Requests", all_requests_path, class: "navbar-item" %>
                <%= link_to 'Offers Sent', my_offers_path, class: "navbar-item" %>
                </div>
            </div>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Orders</a>
                <div class="navbar-dropdown">
                  <%= link_to 'Selling Orders', selling_orders_path, class: "navbar-item" %>
                  <%= link_to 'Buying Orders', buying_orders_path, class: "navbar-item" %>
                </div>
            </div>

            <%= link_to 'Earnings', dashboard_path, class: 'navbar-item' %>
            <%= link_to 'Messages', dashboard_path, class: 'navbar-item' %>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">Settings</a>
                <div class="navbar-dropdown">
                  <%= link_to "Payment Method", settings_payment_path, class: "navbar-item" %>
                  <%= link_to "Payout Method", settings_payout_path, class: "navbar-item" %>
                </div>
            </div>
        </div>
      </div>
    </nav>

  <% end %>
  
  <script>
    $(document).ready(function() {

// Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        $(".navbar-burger").toggleClass("is-active");
        $(".navbar-menu").toggleClass("is-active");

      });
    });
  </script>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
    <script>
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          new Noty ({
            type: '<%= type %>',
            layout: 'bottomRight',
            timeout: '3000',
            theme: 'sunset',
            text: '<%= value %>'
          }).show();
        <% end %>
    </script>
<% end %>