config/routes.rb
Rails.application.routes.draw do
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  post '/users/edit', to: 'users#update'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  
  get '/all-requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/gigs/:id/checkout/:pricing_type', to: 'gigs#checkout', as: 'checkout'

  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post '/users/edit_phone', to: 'users#callback_phone'
  post '/settings/payment', to: 'users#update_payment', as: 'update_payment'
  post '/settings/payout', to: 'users#update_payout', as: 'update_payout'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accepted', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  resources :requests
  
  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create]
  end

  devise_for :users, 
              path: "", 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  root 'pages#home'
end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :pricings
  has_many :orders
  has_many :reviews
  has_many_attached :photos
  has_rich_text :description
  accepts_nested_attributes_for :pricings

  validates :title, presence: { message: 'Cannot be blank'}

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:stars).round(1)
  end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  protect_from_forgery except: [:upload_photo]
  before_action :authenticate_user!, except: [:show]
  before_action :set_gig, except: [:new, :create]
  before_action :is_authorized, only: [:edit, :udpate, :upload_photo, :delete_photo]
  before_action :set_step, only: [:update, :edit]
  before_action :set_categories, only: [:new, :edit, :show]

  def new
    @gig = current_user.gigs.build
  end

  def create
    @gig = current_user.gigs.build(gig_params)

    if @gig.save
      @gig.pricings.create(Pricing.pricing_types.values.map{ |x| {pricing_type: x}})
      redirect_to edit_gig_path(@gig), notice: 'Save...'
    else
      redirect_to request.referrer, flash: { error: @gig.errors.full_messages }
    end
  end

  def edit
  end

  def update
    if @step == 2
      gig_params[:pricings_attributes].each do |index, pricing|
        if @gig.has_single_pricing && pricing[:pricing_type] != Pricing.pricing_types.key(0)
          next;
        else
          if pricing[:title].blank? || pricing[:description].blank? || pricing[:delivery_time].blank? || pricing[:price].blank?
            return redirect_to request.referrer, flash: {error: 'Invalid pricing'}
          end
      end
    end
  end

  if @step == 3 && gig_params[:description].blank?
    return redirect_to request.referrer, flash: {error: "Description cannot be blank"}
  end

  if @step == 4 && @gig.photos.blank?
    return redirect_to request.referrer, flash: {error: "You don't have any photos..."}
  end

  if @step == 5
    @gig.pricings.each do |pricing|
      if @gig.has_single_pricing && !pricing.basic?
        next;
      else
        if pricing[:title].blank? || pricing[:description].blank? || pricing[:delivery_time].blank? || pricing[:price].blank?
          return redirect_to edit_gig_path(@gig, step: 2), flash: {error: "Invalid pricing"}
      end
    end
  end

  if @gig.description.blank?
     return redirect_to edit_gig_path(@gig, step: 3), flash: {error: "Description can't be blank..."}
    elsif @gig.photos.blank?
      return redirect_to edit_gig_path(@gig, step: 4), flash: {error: "You don't have any photos..."}
    end
  end

  if @gig.update(gig_params)
    flash[:notice] = "Save..."
  else
    return redirect_to request.referrer, flash: {error: @gig.errors.full_messages}
  end

  if @step < 5
    redirect_to edit_gig_path(@gig, step: @step + 1)
    else
      redirect_to dashboard_path
    end
  end

  def show
    
  end

  def upload_photo
      @gig.photos.attach(params[:file])
      render json: { success: true }
  end

  def delete_photo
    @image = ActiveStorage::Attachment.find(params[:photo_id])
    @image.purge
    redirect_to edit_gig_path(@gig, step: 4)
  end

  def checkout
    if current_user.stripe_id
      @stripe_customer = Stripe::Customer.retrieve(current_user.stripe_id)

      @gig = Gig.find(params[:id])
      @pricing = @gig.pricings.find_by(pricing_type: params[:pricing_type])
    else
      redirect_to settings_payment_path, alert: "Please add your card first"
    end
  end

  private

  def set_step
    @step = params[:step].to_i > 0 ? params[:step].to_i : 1
    if @step > 5
      @step = 5
    end
  end

  def set_categories
    @categories = Category.all
  end

  def gig_params
    params.require(:gig).permit(:title, :video, :description, :active, :category_id, :has_single_pricing, 
                                pricings_attributes: [:id, :title, :description, :delivery_time, :price, :pricing_type])
  end

  def set_gig
    @gig = Gig.find(params[:id])
  end

  def is_authorized
    redirect_to root_path, alert: 'You do not have permission...' unless current_user.id == @gig.user_id
  end
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/gigs/_step1.html.erb
<div class="step-content <%= 'is-active' if @step == 1 %>"> 
    <div class='field'>
        <label class='label'>Gig Title</label>
        <%= f.text_area :title, autocomplete: 'title', class: 'textarea' %>
    </div>

    <div class='field'>
        <label class='label'>Category</label>
        <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }, selected: @gig.category_id)) %>
    </div>
    
    <div class='field'>
        <label class='checkbox'>
            <%= f.check_box :has_single_pricing, class: 'checkbox', onchange: "this.form.submit();" %> Has Single Price
        </label>
    </div>
</div>

app/views/gigs/_step2.html.erb
<div class="step-content <%= 'is-active' if @step == 2 %>">
    <div class='field'>
        <div class='control'>
            <div class='columns has-text-centered'>
                <%= f.fields_for :pricings, @gig.pricings.order(:pricing_type) do |p| %>
                    <div class="column <%= 'is-4 is-offset-4' if @gig.has_single_pricing && p.object.basic? %>
                                        <%= 'is-hidden' if @gig.has_single_pricing && !p.object.basic? %>">
                      <label class='label'><%= p.object.pricing_type.capitalize %></label>                  
                      <%= p.hidden_field :pricing_type %>

                      <div class='control'>
                        <%= p.text_field :title, placeholder: 'Tile', class: 'input is-radiusless' %>
                      </div>

                      <div class='control'>
                        <%= p.text_area :description, placeholder: 'Description', class: 'textarea is-radiusless' %>
                      </div>

                      <div class='control has-icons-right'>
                        <%= p.number_field :delivery_time, placeholder: 'Delivery Time', class: 'input is-radiusless', default: 1 %>
                        <span class='icon is-small is-right'>days</span>
                      </div>

                       <div class='control has-icons-right'>
                        <%= p.number_field :price, placeholder: 'Price', class: 'input is-radiusless', default: 1 %>
                        <span class='icon is-small is-right'>$</span>
                      </div>
                </div>
            <% end %>
            </div>
        </div>
    </div>
</div>

app/views/gigs/_step3.html.erb
<div class='step-content <%= 'is-active' if @step == 3 %>'>
    <div class='field'>
        <label class='label'>Description</label>
        <%= f.rich_text_area :description, rows: 50, cols: 50 %>
    </div>
</div>

app/views/gigs/_step4.html.erb
<div class="step-content <%= 'is-active' if @step == 4 %>">
    <div class="field">
        <label class="label">Youtube Code</label>
        <%= f.text_field :video, autocomplete: "video url", class: "input" %>
    </div>

    <div class="field">
        <label class="label">Build your Gig Gallery</label>
        <div class="control">
            <div class="m-b-20">
                <div class="dropzone" id="myDropZone" action="/gigs/<%= @gig.id %>/upload_photo"></div>
            </div>

            <div class="columns is-multiline" style: width: 100%>
            <% @gig.photos.each do |photo| %>
                    <div class="column is-one-fifth">
                        <div class="card is-image">
                            <div class="card-image">
                                <%= link_to 'Remove', delete_photo_gig_url(photo_id: photo.id, id: @gig.id, step: @step), 
                                                      method: :delete, 
                                                      data: { confirm: 'Are you sure?'}, 
                                                      class: 'delete delete-file is-pulled-right', 
                                                      style: 'z-index: 100' %>
                                <figure class="image is-4by3">
                                    <%= image_tag url_for(photo) %>
                                </figure>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
    Dropzone.options.myDropZone = {
        paramName: "file",
        maxFilesize: 2,
        acceptedFiles: "image/*",
        init: function() {
            this.on('complete', function(file) {
                location.reload();
            })
        }
    }
</script>

app/views/gigs/_step5.html.erb
<div class="step-content has-text-centered <%= 'is-active' if @step == 5 %>">
    <div>
        <%= hidden_field_tag 'active', 'true' if @step == 5 %>
        <strong class='is-size-2'>Almost there...</strong>
        <p>Let's publish your Gig & get some buyers rolling in.</p>
    </div>
</div>

<div class='field is-grouped is-grouped-centered m-t-25'>
    <p class='control <%= 'is-hidden' if @step <= 1 %>'>
        <%= link_to 'Back', edit_gig_path(@gig, step: @step -1), class: 'button is-light' %>
    </p>

    <p class='control'>
        <% if @step != 5 %>
            <%= f.submit 'Save & Continue', class: 'button is-primary' %>
        <% else %>
            <%= link_to 'Publish', gig_path(@gig.id, gig: {active: true}, step: @step), 
                                            method: :put, 
                                            data: {confirm: "Do you want to publish this gig?"},
                                            class: 'button is-danger' %>
        <% end %>
    </p>
</div>

app/views/gigs/checkout.html.erb
<section class="section">
    <div class="container">
        <%= form_with model: [@gig, @gig.orders.new] do |f| %>
            <%= hidden_field_tag 'pricing_type', @pricing.pricing_type %>

            <div class="columns">
                <!-- LEFT SIDE -->
                <div class="column is-two-thirds">
                    <div class="columns is-multiline">
                        <div class="column is-full">
                            <div class="card">
                                <div class="card-content">
                                    <div class="content">
                                        <p class="title is-5">Payment Options</p>
                                    </div>
                                    <hr />
                                        <div class="content">
                                        <% @stripe_customer.sources.each do |payment| %>
                                            <div class="control">
                                                <%= radio_button_tag 'payment', payment.id, checked: true %>
                                                <span class="m-l-10">
                                                    <%= payment.brand %> <%= "Card: **** **** **** " + payment.last4 %>
                                                </span>
                                            </div>
                                        <% end %>
                                        <div class="control m-t-20">
                                            <%= radio_button_tag 'payment', 'system' %>
                                            <span class="m-l-10">Your System Wallet</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- RIGHTT SIDE -->
                <div class="column">
                    <div class='columns is-multiline'>
                        <div class="column is-full">
                            <div class="card">
                                <div class="card-content">
                                    <div class="content">
                                        <p class="title is-5">Summary</p>
                                    </div>
                                    <hr />
                                    <article class="media">
                                        <div class="media-content">
                                            <figure class="image is-4by3">
                                                <%= image_tag gig_cover(@gig) %>
                                            </figure>
                                        </div>
                                        <div class="media-right">
                                            <strong><%= @gig.title %></strong>
                                        </div>
                                    </article>

                                     <article class="media">
                                        <div class="media-content">
                                            Subtotal
                                        </div>
                                        <div class="media-right">
                                            $<%= '%.2f' % @pricing.price %>
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Service fee (10%)
                                        </div>
                                        <div class="media-right">
                                            $<%= '%.2f' % (@pricing.price * 0.1) %>
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Total
                                        </div>
                                        <div class="media-right">
                                            $<%= '%.2f' % (@pricing.price * 1.1) %>
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Total delivery time
                                        </div>
                                        <div class="media-right">
                                            <%= pluralize(@pricing.delivery_time, 'day') %>
                                        </div>
                                    </article>

                                    <%= f.submit "Place Your Order", class: "button is-fullwidth is-danger", data: {confirm: "Are you sure?"} %>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/gigs/edit.html.erb
<section class="section"></section>
  <div class="container">
    <div class="steps" id="stepsDemo">

      <!-- 5 STEPS -->
      <div class="step-item <%= 'is-active' if @step == 1 %> <%= 'is-completed' if @step > 1 %>">
        <div class="step-marker">1</div>
        <div class="step-details">
          <p class="step-title">Overview</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active' if @step == 2 %> <%= 'is-completed' if @step > 2 %>">
        <div class="step-marker">2</div>
        <div class="step-details">
          <p class="step-title">Pricing</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active' if @step == 3 %> <%= 'is-completed' if @step > 3 %>">
        <div class="step-marker">3</div>
        <div class="step-details">
          <p class="step-title">Description</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active' if @step == 4 %> <%= 'is-completed' if @step > 4 %>">
        <div class="step-marker">4</div>
        <div class="step-details">
          <p class="step-title">Gallery</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active' if @step == 5 %> <%= 'is-completed' if @step > 5 %>">
        <div class="step-marker">5</div>
        <div class="step-details">
          <p class="step-title">Publish</p>
        </div>
      </div>

      <!-- FORM TO CREATE A NEW GIG HERE-->
        <%= form_for @gig, html: { class: 'steps-content m-l-100 m-r-100' } do |f| %>
          <%= hidden_field_tag 'step', @step %>
          
          <%= render 'step1', f: f %>
          <%= render 'step2', f: f %>
          <%= render 'step3', f: f %>
          <%= render 'step4', f: f %>
          <%= render 'step5', f: f %>
        <% end %>
      
    </div>
  </div>
</section>

app/views/gigs/new.html.erb
<section class="section">
  <div class="container">
    <div class="steps" id="stepsDemo">

      <!-- 5 STEPS -->
      <div class="step-item is-active is-primary">
        <div class="step-marker">1</div>
        <div class="step-details">
          <p class="step-title">Overview</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">2</div>
        <div class="step-details">
          <p class="step-title">Pricing</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">3</div>
        <div class="step-details">
          <p class="step-title">Description</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">4</div>
        <div class="step-details">
          <p class="step-title">Gallery</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">5</div>
        <div class="step-details">
          <p class="step-title">Publish</p>
        </div>
      </div>

      <!-- FORM TO CREATE A NEW GIG HERE-->
        <%= form_for @gig, html: { class: 'steps-content m-l-100 m-r-100' } do |f| %>
          <div class='field'>
            <label class='label'>Gig Title</label>
            <%= f.text_area :title, autocomplete: 'title', class: 'textarea' %>
          </div>

          <div class='field'>
            <label class='label'>Category</label>
            <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] })) %>
          </div>

          <div class='field is-grouped is-grouped-centered m-t-25'>
            <a href='' data-nav="previous" class='button is-light'>Cancel</a>
            <%= f.submit 'Save & Continue', class: 'button is-primary' %>
          </div>
        <% end %>
      
    </div>
  </div>
</section>

app/views/gigs/show.html.erb
<% content_for :head do %>
    <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<%= render 'shared/categories' %>

<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <div class="columns is-multiline">

                    <!-- Carousel -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">
                                <div class="content">
                                    <p class="title is-4"><%= @gig.title %></p>
                                </div>
                                <hr />
                                <div class="hero-carousel" id="carousel-photo">
                                <% @gig.photos.each do |photo| %>
                                    <div class="carousel-item has-background image is-16by9">
                                        <%= image_tag url_for(photo), class: "is-background", width: "100%" %>
                                    </div>
                                <% end %>
                                <% if @gig.video.present? %>
                                    <div class="video-container">
                                        <iframe  src="https://www.youtube.com/embed/<%= @gig.video %>" allowfullscreen></iframe>
                                    </div>
                                <% end %>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- About Section -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content">
                                <article class="media">
                                    <div class="media-content">
                                        <p><strong>About This Gig</strong></p>
                                        <hr />
                                        <%= @gig.description %>
                                    </div>
                                </article>
                            </div>
                        </div>                      
                    </div>
                    
                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Pricing Section -->
                    <div class="column is-full">
                    <!-- Pricing Section -->
                        <div class="column is-full">

                            <div class="tabs is-fullwidth" id="tabs">
                                <ul>
                                    <% Pricing.pricing_types.each do |key, value| %>
                                        <li class="tab <%= 'is-active' if value == 0 %>" data-tab="<%= key %>" style="<%= 'display: none' if @gig.has_single_pricing && value != 0 %>">
                                            <a><%= key.capitalize %></a>
                                        </li>
                                    <% end %>
                                </ul>
                            </div>

                            <div class="tabs-content">

                            <% @gig.pricings.each do |p| %>
                                <div class="tab-content" id="tab-<%= p.pricing_type %>" style="<%= 'display: none' if !p.basic? %>">
                                    <div class="card">
                                        <div class="card-content">
                                            <div class="media">
                                                <div class="media-content">
                                                    <strong><%= p.title %></strong>                                                                                                        
                                                </div>
                                                <div class="media-right">
                                                    <p class="title is-4">$<%= p.price %></p>
                                                </div>                                                
                                            </div>
                                            <div class="content f-15">
                                                <p class="m-t-30"><%= p.description %></p>
                                                <p class="m-t-30">
                                                    <strong><i class="far fa-clock"></i> <%= pluralize(p.delivery_time, 'Day') %> Delivery</strong>                                                    
                                                </p>
                                            </div>
                                            <% if (!user_signed_in? && @gig.active) || (user_signed_in? && @gig.active && @gig.user_id != current_user.id) %>
                                                <%= link_to "Continue ($#{p.price})", checkout_path(id: @gig.id, pricing_type: p.pricing_type), class: "button is-fullwidth is-danger" %>                                        
                                            <% else %>
                                                <button class="button is-fullwidth is-danger" disabled>Not Available</button>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                            </div>

                        </div>                      
                    </div>

                    <!-- Profile Section -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content is-horizontal-center is-flex">
                                <%= link_to users_path(@gig.user) do %>
                                    <figure class="image is-96x96">
                                        <%= image_tag avatar_url(@gig.user), class: "is-rounded" %>
                                    </figure>
                                <% end %>
                            </div>
                            <div class="card-content f-15">
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= @gig.user.full_name %></p>
                                    <button class="button is-black is-outlined is-fullwidth">Contact me</button>
                                </div>
                                <article class="media">
                                    <div class="media-content">
                                        <i class="fas fa-user m-r-5"></i> Member since
                                    </div>
                                    <div class="media-right">
                                        <%= @gig.user.created_at.strftime('%b %Y') %>
                                    </div>
                                </article>
                                <article class="media">
                                    <div class="media-content">
                                        <i class="fas fa-map-marker-alt m-r-5"></i> From
                                    </div>
                                    <div class="media-right">
                                        <%= @gig.user.from %>
                                    </div>
                                </article>
                                <article class="media">
                                    <div class="media-content">
                                        <%= @gig.user.about %>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>

<script>
    BulmaCarousel.attach('#carousel-photo', {
        slidesToScroll: 1,
        slidesToShow: 1
    });

    $(document).ready(function() {
        $('#tabs li').on('click', function() {
            var type = $(this).data('tab');

            $('#tabs li').removeClass('is-active');
            $(this).addClass('is-active');

            $('.tab-content').hide();
            $('#tab-' + type).show();
        })
    })
</script>